### ISSUE TITLE
Compatbility Postgrey 1.34 and Perl <5.20

### ISSUE THREAD

**Issue by alextux** [YunoHost/yunohost-config-postfix#3]
Hi,
It seems there a compatbility problem when you install yunohost package on a debian wheezy.
Perl version is 5.14 or 5.18 on debian wheezy and the last version of postgrey in the debian stable repository is not compatible with those perl version.
I have apply this patch : https://github.com/yasuhirokimura/postgrey/commit/9673b54064691a5b9c295ffea340d8a1f9ee1cb8and all work find.

Thanks

**Comment by julienmalik** [comment]
Perl is 5.14 on debian wheezy, and 5.20 on jessie : https://packages.debian.org/search?keywords=perl
